# Generated by Django 4.1.2 on 2022-10-20 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=64)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('code', models.TextField()),
                ('country', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=64)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('code', models.TextField()),
                ('country', models.TextField()),
                ('name', models.TextField()),
                ('siret', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=64)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('code', models.TextField()),
                ('country', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('role', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
