# Generated by Django 4.1.2 on 2022-10-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0003_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entreprise',
            new_name='Entreprises',
        ),
    ]
