# Generated by Django 4.1.2 on 2022-11-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_city_alter_user_code_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='entreprise',
            options={'verbose_name': 'Entreprise'},
        ),
        migrations.AlterModelOptions(
            name='personne',
            options={'verbose_name': 'Personne'},
        ),
    ]
