# Generated by Django 4.1.2 on 2022-10-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0003_initial'),
        ('User', '0002_rename_entreprise_entreprises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entreprises',
            new_name='Entreprise',
        ),
        migrations.RenameModel(
            old_name='Personnes',
            new_name='Personne',
        ),
    ]
