# Generated by Django 4.1.2 on 2022-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_entreprises_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='admin',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='admin',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='admin',
            name='street',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='street',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='street',
            field=models.CharField(max_length=64),
        ),
    ]
