# Generated by Django 4.1.2 on 2022-11-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_admin_options_alter_entreprise_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='role',
        ),
    ]
