# Generated by Django 4.1.4 on 2022-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='numéro de téléphone'),
        ),
    ]
