# Generated by Django 4.1.2 on 2022-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_admin_city_alter_admin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personne',
            name='code',
            field=models.IntegerField(),
        ),
    ]
