# Generated by Django 4.1.4 on 2023-01-22 14:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_personne_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilpic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='user/pp/default.webp', force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[200, 200], upload_to='user/pp/'),
        ),
    ]
