# Generated by Django 4.1.2 on 2022-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_admin_code_alter_entreprise_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='firstname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lastname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(max_length=64),
        ),
    ]
