# Generated by Django 4.1.2 on 2022-10-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_personne_firstname_alter_personne_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Eleve'), ('TEACHER', 'Professeur')], max_length=20),
        ),
    ]
