# Generated by Django 4.1.2 on 2022-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_profilpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilpic',
            field=models.ImageField(default='default.png', upload_to='user/ProfilPic'),
        ),
    ]
