# Generated by Django 4.1.7 on 2023-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_profilpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
