# Generated by Django 4.1.2 on 2022-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_profilpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
