# Generated by Django 4.1.2 on 2022-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_user_city_remove_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilpic',
            field=models.ImageField(default='default.png', null=True, upload_to='user/ProfilPic'),
        ),
    ]
