# Generated by Django 4.1.2 on 2022-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_user_username_alter_user_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
