# Generated by Django 4.1.2 on 2022-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilpic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='user/pp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=128, unique=True, verbose_name='email'),
        ),
    ]
