# Generated by Django 4.1.2 on 2022-11-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_alter_user_profilpic_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='profilpic',
            field=models.ImageField(default='user/pp/default.png', upload_to='user/pp'),
        ),
    ]
