# Generated by Django 4.1.2 on 2022-12-13 14:59

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_alter_user_profilpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='firstname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='lastname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilpic',
            field=django_resized.forms.ResizedImageField(crop=[0, 0, 200, 200], default='user/pp/default.webp', force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[200, 200], upload_to='user/pp'),
        ),
    ]
