# Generated by Django 4.1.2 on 2022-11-15 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentationEntreprise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.entreprise')),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.introduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('mention', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personne')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personne')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='introduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.introduction'),
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personne')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv')),
            ],
        ),
    ]
