# Generated by Django 4.1.4 on 2023-01-02 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_personne_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('ord_xp', models.IntegerField(default=1, null=True)),
                ('ord_form', models.IntegerField(default=2, null=True)),
                ('ord_comp', models.IntegerField(default=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentationEntreprise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.entreprise')),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.introduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('mention', models.TextField(null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='introduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.introduction'),
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv')),
            ],
        ),
    ]
