# Generated by Django 4.1.2 on 2022-11-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Presentation', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.entreprise'),
        ),
        migrations.AddField(
            model_name='presentationentreprise',
            name='introduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.introduction'),
        ),
        migrations.AddField(
            model_name='formation',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie'),
        ),
        migrations.AddField(
            model_name='formation',
            name='certifie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
        migrations.AddField(
            model_name='formation',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv'),
        ),
        migrations.AddField(
            model_name='experience',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie'),
        ),
        migrations.AddField(
            model_name='experience',
            name='certifie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv'),
        ),
        migrations.AddField(
            model_name='cv',
            name='introduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.introduction'),
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
        migrations.AddField(
            model_name='competences',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie'),
        ),
        migrations.AddField(
            model_name='competences',
            name='certifie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
        migrations.AddField(
            model_name='competences',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.cv'),
        ),
    ]
