# Generated by Django 4.1.2 on 2022-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competences',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='presentation_ptr',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='presentationentreprise',
            name='presentation_ptr',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Competences',
        ),
        migrations.DeleteModel(
            name='Cv',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
        migrations.DeleteModel(
            name='PresentationEntreprise',
        ),
    ]
