# Generated by Django 4.1.2 on 2022-11-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competences',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='ord_comp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='ord_form',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='ord_xp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
