# Generated by Django 4.1.4 on 2023-01-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_personne_slug'),
        ('Presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='certifie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.personne'),
        ),
    ]
