# Generated by Django 4.1.4 on 2023-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0002_alter_competence_certifie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presentationentreprise',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
