# Generated by Django 4.1.2 on 2022-11-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='ord_comp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ord_form',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ord_xp',
            field=models.IntegerField(null=True),
        ),
    ]
