# Generated by Django 4.1.2 on 2022-10-20 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Presentation', '0002_remove_competences_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentationEntreprise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.entreprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('mention', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personnes')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personnes')),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('eleves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personnes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Presentation.categorie')),
                ('certifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.personnes')),
            ],
        ),
    ]
