# Generated by Django 4.1.2 on 2022-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0002_competences_order_cv_ord_comp_cv_ord_form_cv_ord_xp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
