# Generated by Django 4.1.2 on 2022-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0003_alter_cv_ord_comp_alter_cv_ord_form_alter_cv_ord_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='ord_comp',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ord_form',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ord_xp',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
